# Generated by Django 4.0.3 on 2022-03-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0003_alter_paste_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='paste_hash',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
